# Scandium-44 ion source with half-life of 3.97 hrs (14292 seconds)

# -------------------------------------------------------------
# Source Geometry
# -------------------------------------------------------------
#/gate/source/addSource				    point
#/gate/source/point/gps/pos/type		    Volume
#/gate/source/point/gps/pos/shape		Sphere
#/gate/source/point/gps/pos/radius	    0.1 mm
#/gate/source/point/gps/ang/type			iso
#/gate/source/point/gps/centre           0. 0. 0. mm

# -------------------------------------------------------------
# Two Point Sources
# -------------------------------------------------------------
/gate/source/addSource				    point1
/gate/source/point1/gps/pos/type		    Volume
/gate/source/point1/gps/pos/shape		Sphere
/gate/source/point1/gps/pos/radius	    0.1 mm
/gate/source/point1/gps/ang/type			iso
/gate/source/point1/gps/centre           5.5 0. 0. mm
/gate/source/point1/gps/particle                 ion
/gate/source/point1/gps/ion                      21 44 0 0           # Z = 21, A = 44
/gate/source/point1/gps/ene/mono                 0. keV
/gate/source/point1/setActivity                  1 MBq
/gate/source/point1/setForcedUnstableFlag        true
/gate/source/point1/useDefaultHalfLife

/gate/source/addSource				    point2
/gate/source/point2/gps/pos/type		    Volume
/gate/source/point2/gps/pos/shape		Sphere
/gate/source/point2/gps/pos/radius	    0.1 mm
/gate/source/point2/gps/ang/type			iso
/gate/source/point2/gps/centre           -5.5 0. 0. mm
/gate/source/point2/gps/particle                 ion
/gate/source/point2/gps/ion                      21 44 0 0           # Z = 21, A = 44
/gate/source/point2/gps/ene/mono                 0. keV
/gate/source/point2/setActivity                  1 MBq
/gate/source/point2/setForcedUnstableFlag        true
/gate/source/point2/useDefaultHalfLife

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Sc-44 as ion source 
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#/gate/source/point/gps/particle                 ion
#/gate/source/point/gps/ion                      21 44 0 0           # Z = 21, A = 44
#/gate/source/point/gps/ene/mono                 0. keV
#/gate/source/point/setActivity                  2 MBq
#/gate/source/point/setForcedUnstableFlag        true
##/gate/source/point/setForcedHalfLife            14292 s
#/gate/source/point/useDefaultHalfLife


# =================================================================================
# ---------------------------------------------------------------------------------
#   NOTE: In Physics.mac file, be sure to add process 'RadioactiveDecay' in order
#         to get decay physics for ion source.
#           - /gate/physics/addProcess RadioactiveDecay
# =================================================================================