# -------------------------------------------------------------
# Source Geometry
# -------------------------------------------------------------
/gate/source/addSource				    point
/gate/source/point/gps/pos/type		    Volume
/gate/source/point/gps/pos/shape		Sphere
/gate/source/point/gps/pos/radius	    0.1 mm
/gate/source/point/gps/ang/type			iso

/gate/source/point/gps/particle         ion
/gate/source/point/gps/ion              27 57 0 0
/gate/source/point/gps/energy           MeV