# Gallium-68 ion source with half-life of 67.83 min (4070 seconds)

# -------------------------------------------------------------
# Source Geometry
# -------------------------------------------------------------
/gate/source/addSource				    point
/gate/source/point/gps/pos/type		    Volume
/gate/source/point/gps/pos/shape		Sphere
/gate/source/point/gps/pos/radius	    0.1 mm
/gate/source/point/gps/ang/type			iso
/gate/source/point/gps/centre           0. 0. 0. mm

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 68-Ga as ion source 
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/gate/source/point/gps/particle                 ion
/gate/source/point/gps/ion                      31 68 0 0           # Z = 31, A = 68
/gate/source/point/gps/ene/mono                 0. keV
/gate/source/point/setActivity                  2 MBq
/gate/source/point/setForcedUnstableFlag        true
#/gate/source/point/setForcedHalfLife            4070 s
/gate/source/point/useDefaultHalfLife


# =================================================================================
# ---------------------------------------------------------------------------------
#   NOTE: In Physics.mac file, be sure to add process 'RadioactiveDecay' in order
#         to get decay physics for ion source.
#           - /gate/physics/addProcess RadioactiveDecay
# =================================================================================