# Arsenic-72 ion source with half-life of 26 hrs (93600 seconds)

# -------------------------------------------------------------
# Source Geometry
# -------------------------------------------------------------
/gate/source/addSource				    point
/gate/source/point/gps/pos/type		    Volume
/gate/source/point/gps/pos/shape		Sphere
/gate/source/point/gps/pos/radius	    0.1 mm
/gate/source/point/gps/ang/type			iso
/gate/source/point/gps/centre           0. 0. 0. mm

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 71-As as ion source 
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/gate/source/point/gps/particle                 ion
/gate/source/point/gps/ion                      33 72 0 0           # Z = 33, A = 72
/gate/source/point/gps/ene/mono                 0. keV
/gate/source/point/setActivity                  1.5 MBq
/gate/source/point/setForcedUnstableFlag        true
#/gate/source/point/setForcedHalfLife            93600 s
/gate/source/point/useDefaultHalfLife


# =================================================================================
# ---------------------------------------------------------------------------------
#   NOTE: In Physics.mac file, be sure to add process 'RadioactiveDecay' in order
#         to get decay physics for ion source.
#           - /gate/physics/addProcess RadioactiveDecay
# =================================================================================