#----------------------------
# Physics list 
#----------------------------
/gate/physics/addProcess     RadioactiveDecay
/gate/physics/addPhysicsList emstandard_opt4

#/gate/physics/processList Enabled
#/gate/physics/processList Initialized  

#----------------------------
# Cut 
#----------------------------

/gate/physics/Gamma/SetCutInRegion	    world	1 mm
/gate/physics/Electron/SetCutInRegion	world	1000 km
/gate/physics/Positron/SetCutInRegion	world	1 mm